#!/bin/bash
export TMPDIR="/home/skladis/tmp"

echo "DEPLOYING SKLADIS FRONTEND"
echo "=========================="

ssh-keyscan github.com > ~/.ssh/known_hosts
cd ~/app/skladis-frontend
git pull
podman build --cgroup-manager=cgroupfs -t skladis-frontend .
sudo systemctl restart skladis.service
